//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goz_klinigi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Göz_kliniğiEntities : DbContext
    {
        public Göz_kliniğiEntities()
            : base("name=Göz_kliniğiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOKTOR> DOKTORs { get; set; }
        public virtual DbSet<FATURE> FATUREs { get; set; }
        public virtual DbSet<HASTA> HASTAs { get; set; }
        public virtual DbSet<ODEME> ODEMEs { get; set; }
        public virtual DbSet<RANDEVU> RANDEVUs { get; set; }
        public object DOKTOR { get; internal set; }
    }
}
